name: safehaven

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: safehaven
    volumes:
      - .pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
